function cHandle = plotDots(cX, cData, set)
%plotDots Summary of this function goes here
%   Detailed explanation goes here

cHandle = scatter(cX+set.offsetToRight, cData, set.size, "O", ...
    "MarkerEdgeColor", set.EdgeColor, ...
    "MarkerFaceColor", set.MarkerFaceColor, ...
    'MarkerFaceAlpha', set.MarkerFaceAlpha, ...
    'MarkerEdgeAlpha', set.MarkerEdgeAlpha);
end
