function cHandle = plotDots(cX, cData, set)
%plotDots Summary of this function goes here
%   Detailed explanation goes here

cHandle = scatter(cX+set.offsetToRight-0.5*set.width+set.width*rand(size(cData,1),1), cData, set.size, "O", ...
    "MarkerEdgeColor", set.EdgeColor, ...
    "MarkerFaceColor", set.MarkerFaceColor, ...
    'MarkerFaceAlpha', set.MarkerFaceAlpha, ...
    'MarkerEdgeAlpha', set.MarkerEdgeAlpha);
end
