function cHandle = plotMeanStar(cX, cData, set)
%PLOTMEANSTAR Summary of this function goes here
%   Detailed explanation goes here

cHandle = scatter(cX+set.offsetToRight, mean(cData), set.size, 'd', ...
    'MarkerEdgeColor', set.EdgeColor, ...
    'MarkerFaceColor', set.MarkerFaceColor, ...
    'MarkerFaceAlpha', set.MarkerFaceAlpha, ...
    'MarkerEdgeAlpha', set.MarkerEdgeAlpha);
end
