function [cHandle, cMean] = plotMeanStar(cX, cData, set)
%PLOTMEANSTAR Summary of this function goes here
%   Detailed explanation goes here
cMean = mean(cData); 
cHandle = scatter(cX+set.offsetToRight, cMean, set.size, 'd', ...
    'MarkerEdgeColor', set.EdgeColor, ...
    'MarkerFaceColor', set.MarkerFaceColor, ...
    'MarkerFaceAlpha', set.MarkerFaceAlpha, ...
    'MarkerEdgeAlpha', set.MarkerEdgeAlpha);
end
